[versions]
kotlin = "2.1.0"
kotlinSymbolProcessing = "2.0.21-1.0.28"
compileSdk = "35"
minSdk = "24"
targetSdk = "35"

# Core
coroutines = "1.8.1"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"

# Compose
composeBom = "2025.06.00"
composeFoundation = "1.8.2"
material3Android = "1.3.2"
material3WindowSize = "1.3.2"
navigationCompose = "2.9.0"
material = "1.9.0"

# Network
retrofit = "2.11.0"
okhttp = "4.12.0"
serializationJson = "1.7.3"
kotlinxSerializationConverter = "1.0.0"

# Database
room = "2.7.1"
datastorePreferences = "1.1.7"

# DI
koin-bom = "3.5.3"

# UI
coil = "2.7.0"
lottie = "6.4.0"
systemUiController = "0.28.0"
libphonenumber = "8.2.0"
timber = "5.0.1"

# Keelo Specific
socketio = "2.1.0"
workManager = "2.9.0"
accompanistPermissions = "0.34.0"

# Build
androidGradlePlugin = "8.10.1"
spotless = "6.25.0"
detekt = "1.23.6"
testLogger = "3.2.0"

# Testing
junit = "5.12.2"
androidJUnit5 = "1.11.2.0"
kluent = "1.73"
testRunner = "1.6.2"
mockk = "1.13.13"
espresso = "3.6.1"
coreTesting = "2.2.0"

navigation = "2.9.0"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeFoundation" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
material3WindowSize = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3WindowSize" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

retrofitCore = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
kotlinxSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxSerializationConverter" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
datastorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
systemUiController = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "systemUiController" }
libphonenumber = { group = "com.googlecode.libphonenumber", name = "libphonenumber", version.ref = "libphonenumber" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

socketio = { module = "io.socket:socket.io-client", version.ref = "socketio" }
workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }

junit = { module = "junit:junit", version.ref = "junit" }
testCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kluent = { module = "org.amshove.kluent:kluent-android", version.ref = "kluent" }
testRunner = { module = "androidx.test:runner", version.ref = "testRunner" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
coreTesting = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
konsist = "com.lemonappdev:konsist:0.16.0"

[bundles]
retrofit = ["retrofitCore", "kotlinxSerializationConverter", "serializationJson", "okhttp", "okhttpInterceptor"]
compose = ["composeFoundation", "androidx-ui", "androidx-ui-graphics", "androidx-ui-tooling", "androidx-ui-tooling-preview", "lottie", "coil", "androidx-material-icons-extended"]
room = ["roomKtx", "roomRuntime"]
test = ["testCoroutines", "kluent", "testRunner", "espresso", "mockk", "coreTesting", "junitJupiterApi", "junitJupiterEngine", "konsist", "junit"]
keelo = ["socketio", "workManager", "accompanistPermissions"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-symbolProcessing = { id = "com.google.devtools.ksp", version.ref = "kotlinSymbolProcessing" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
junit5Android = { id = "de.mannodermaus.android-junit5", version.ref = "androidJUnit5" }
testLogger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }
safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }